// This file is autogenerated. Changes will be overwritten.
#include "UFQQIFJZKK/moc_protocol_handler.cpp"
#include "UFQQIFJZKK/moc_websocket_client.cpp"
#include "YPKJ5OE7LN/moc_chatwidget.cpp"
#include "YPKJ5OE7LN/moc_contactwidget.cpp"
#include "YPKJ5OE7LN/moc_loginwindow.cpp"
#include "YPKJ5OE7LN/moc_mainwindow.cpp"
#include "YPKJ5OE7LN/moc_messageitem.cpp"
